EDUCATION_VOCABS = [
    {"text": "curriculum", "answer": "subjects taught in a school", "topic": "Education"},
    {"text": "tuition", "answer": "money paid for education", "topic": "Education"},
    {"text": "scholarship", "answer": "financial support for study", "topic": "Education"},
    {"text": "assessment", "answer": "evaluation of performance", "topic": "Education"},
    {"text": "qualification", "answer": "official achievement record", "topic": "Education"},
    {"text": "lecture", "answer": "formal talk for students", "topic": "Education"},
    {"text": "seminar", "answer": "small group discussion class", "topic": "Education"},
    {"text": "vocational", "answer": "related to job skills", "topic": "Education"},
    {"text": "academic", "answer": "related to education", "topic": "Education"},
    {"text": "dropout", "answer": "student who leaves school early", "topic": "Education"},
    {"text": "literacy", "answer": "ability to read and write", "topic": "Education"},
    {"text": "numeracy", "answer": "ability to work with numbers", "topic": "Education"},
    {"text": "enroll", "answer": "officially join a course", "topic": "Education"},
    {"text": "graduate", "answer": "finish university study", "topic": "Education"},
    {"text": "postgraduate", "answer": "study after a degree", "topic": "Education"},
    {"text": "distance learning", "answer": "online education", "topic": "Education"},
    {"text": "discipline", "answer": "field of study", "topic": "Education"},
    {"text": "evaluation", "answer": "judging quality or value", "topic": "Education"},
    {"text": "compulsory", "answer": "required by law", "topic": "Education"},
    {"text": "educational reform", "answer": "changes to education system", "topic": "Education"},
]
