ENVIRONMENT_VOCABS = [
    {"text": "mitigate", "answer": "to make something less severe", "topic": "Environment"},
    {"text": "sustainability", "answer": "ability to maintain resources long-term", "topic": "Environment"},
    {"text": "climate change", "answer": "long-term change in weather patterns", "topic": "Environment"},
    {"text": "global warming", "answer": "rise in global temperatures", "topic": "Environment"},
    {"text": "carbon footprint", "answer": "amount of carbon emissions produced", "topic": "Environment"},
    {"text": "renewable energy", "answer": "energy from natural sources", "topic": "Environment"},
    {"text": "fossil fuels", "answer": "coal, oil, gas used for energy", "topic": "Environment"},
    {"text": "deforestation", "answer": "cutting down forests", "topic": "Environment"},
    {"text": "pollution", "answer": "harmful substances in environment", "topic": "Environment"},
    {"text": "biodiversity", "answer": "variety of living species", "topic": "Environment"},
    {"text": "ecosystem", "answer": "community of living organisms", "topic": "Environment"},
    {"text": "conservation", "answer": "protection of nature", "topic": "Environment"},
    {"text": "endangered species", "answer": "animals at risk of extinction", "topic": "Environment"},
    {"text": "recycling", "answer": "reusing materials", "topic": "Environment"},
    {"text": "waste management", "answer": "handling waste properly", "topic": "Environment"},
    {"text": "air quality", "answer": "cleanliness of air", "topic": "Environment"},
    {"text": "water scarcity", "answer": "lack of fresh water", "topic": "Environment"},
    {"text": "overpopulation", "answer": "too many people", "topic": "Environment"},
    {"text": "environmental awareness", "answer": "understanding environmental issues", "topic": "Environment"},
    {"text": "sustainable development", "answer": "growth without harming future", "topic": "Environment"},
]
