HEALTH_VOCABS = [
    {"text": "well-being", "answer": "state of being healthy and happy", "topic": "Health"},
    {"text": "mental health", "answer": "psychological well-being", "topic": "Health"},
    {"text": "physical fitness", "answer": "body health and strength", "topic": "Health"},
    {"text": "balanced diet", "answer": "healthy mix of foods", "topic": "Health"},
    {"text": "sedentary lifestyle", "answer": "inactive way of living", "topic": "Health"},
    {"text": "obesity", "answer": "excess body fat", "topic": "Health"},
    {"text": "stress management", "answer": "controlling stress levels", "topic": "Health"},
    {"text": "preventive care", "answer": "healthcare to prevent illness", "topic": "Health"},
    {"text": "medical treatment", "answer": "care to cure illness", "topic": "Health"},
    {"text": "public health", "answer": "health of the population", "topic": "Health"},
    {"text": "life expectancy", "answer": "average lifespan", "topic": "Health"},
    {"text": "healthcare system", "answer": "medical services of a country", "topic": "Health"},
    {"text": "vaccination", "answer": "injection to prevent disease", "topic": "Health"},
    {"text": "chronic disease", "answer": "long-term illness", "topic": "Health"},
    {"text": "immune system", "answer": "body defense system", "topic": "Health"},
    {"text": "addiction", "answer": "dependence on substances", "topic": "Health"},
    {"text": "rehabilitation", "answer": "recovery process", "topic": "Health"},
    {"text": "nutrition", "answer": "food and nourishment", "topic": "Health"},
    {"text": "medical expenses", "answer": "cost of healthcare", "topic": "Health"},
    {"text": "healthy lifestyle", "answer": "habits that improve health", "topic": "Health"},
]
