TECHNOLOGY_VOCABS = [
    {"text": "innovation", "answer": "new idea or method", "topic": "Technology"},
    {"text": "automation", "answer": "machines doing tasks", "topic": "Technology"},
    {"text": "artificial intelligence", "answer": "machines simulating intelligence", "topic": "Technology"},
    {"text": "cybersecurity", "answer": "protection of systems", "topic": "Technology"},
    {"text": "digitalization", "answer": "use of digital tech", "topic": "Technology"},
    {"text": "algorithm", "answer": "step-by-step instructions", "topic": "Technology"},
    {"text": "data breach", "answer": "leak of sensitive data", "topic": "Technology"},
    {"text": "cloud computing", "answer": "online data storage", "topic": "Technology"},
    {"text": "user interface", "answer": "how users interact with software", "topic": "Technology"},
    {"text": "bandwidth", "answer": "data transfer capacity", "topic": "Technology"},
    {"text": "device", "answer": "electronic equipment", "topic": "Technology"},
    {"text": "software update", "answer": "new version of software", "topic": "Technology"},
    {"text": "hardware", "answer": "physical components", "topic": "Technology"},
    {"text": "start-up", "answer": "new business", "topic": "Technology"},
    {"text": "virtual reality", "answer": "computer-simulated environment", "topic": "Technology"},
    {"text": "digital divide", "answer": "gap in tech access", "topic": "Technology"},
    {"text": "online privacy", "answer": "protection of personal data", "topic": "Technology"},
    {"text": "automation risk", "answer": "jobs lost to machines", "topic": "Technology"},
    {"text": "remote work", "answer": "working from home", "topic": "Technology"},
    {"text": "technological advancement", "answer": "progress in technology", "topic": "Technology"},
]
