TRAVEL_VOCABS = [
    {"text": "itinerary", "answer": "a planned route or journey", "topic": "Travel"},
    {"text": "accommodation", "answer": "a place to stay", "topic": "Travel"},
    {"text": "destination", "answer": "the place someone is going to", "topic": "Travel"},
    {"text": "commute", "answer": "travel regularly between home and work", "topic": "Travel"},
    {"text": "tourism", "answer": "traveling for pleasure", "topic": "Travel"},
    {"text": "backpacking", "answer": "traveling with minimal luggage", "topic": "Travel"},
    {"text": "visa", "answer": "official permission to enter a country", "topic": "Travel"},
    {"text": "customs", "answer": "border control for goods", "topic": "Travel"},
    {"text": "landmark", "answer": "a famous place or building", "topic": "Travel"},
    {"text": "resort", "answer": "place for vacation", "topic": "Travel"},
    {"text": "delay", "answer": "when something happens later than expected", "topic": "Travel"},
    {"text": "departure", "answer": "the act of leaving", "topic": "Travel"},
    {"text": "arrival", "answer": "the act of reaching a destination", "topic": "Travel"},
    {"text": "scenic", "answer": "having beautiful views", "topic": "Travel"},
    {"text": "overcrowded", "answer": "too many people", "topic": "Travel"},
    {"text": "budget travel", "answer": "traveling cheaply", "topic": "Travel"},
    {"text": "package tour", "answer": "pre-arranged travel plan", "topic": "Travel"},
    {"text": "peak season", "answer": "busiest travel time", "topic": "Travel"},
    {"text": "off-season", "answer": "quiet travel time", "topic": "Travel"},
    {"text": "hospitality", "answer": "friendly treatment of guests", "topic": "Travel"},
]
